accounts/urls.py
from django.urls import path
from .views import (
    register_view,
    login_view,
    logout_view,
    profile_view,
    profile_threads,
    profile_replies,
    profile_reposts,
    follow_toggle,
    profile_followers,
    profile_following,
    profile_edit,
)

app_name = "accounts"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", register_view, name="register"),
    path("profile/<str:username>/", profile_view, name="profile"),
    path("profile/<str:username>/threads/", profile_threads, name="profile_threads"),
    path("profile/<str:username>/replies/", profile_replies, name="profile_replies"),
    path("profile/<str:username>/reposts/", profile_reposts, name="profile_reposts"),
    # htmx follow toggle
    path(
        "follow-toggle/profile/<int:id>/",
        follow_toggle,
        name="follow_toggle",
    ),
    # htmx followers and followings get
    path(
        "profile/<str:username>/followers/", profile_followers, name="profile_followers"
    ),
    path(
        "profile/<str:username>/following/", profile_following, name="profile_following"
    ),
    # edit profile
    path("profile/<int:id>/edit/", profile_edit, name="profile_edit"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("thread.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thread/urls.py
from django.urls import path
from . import views


app_name = "thread"

urlpatterns = [
    path("", views.home, name="home"),
    path("feed/", views.feed, name="feed"),
    path("following-feed/", views.following_feed, name="following_feed"),
    path("search/", views.search, name="search"),
    path("search-query/", views.search_query, name="search_query"),
    path("create-thread/", views.create_thread, name="create_thread"),
    path("create-reply/", views.create_reply, name="create_reply"),
    # htmx form related (thread and comment)
    path(
        "thread-reply-form/<int:id>/",
        views.get_thread_reply_form,
        name="get_thread_reply_form",
    ),
    path(
        "comment-reply-form/<int:id>/",
        views.get_comment_reply_form,
        name="get_comment_reply_form",
    ),
    path("thread-form-unit/", views.get_thread_form_unit, name="get_thread_form_unit"),
    path("reply-form-unit/", views.get_reply_form_unit, name="get_reply_form_unit"),
    # htmx like features related routes
    path(
        "like-toggle/thread/<int:id>/",
        views.like_thread_toggle,
        name="like_thread_toggle",
    ),
    path(
        "like-toggle/comment/<int:id>/",
        views.like_comment_toggle,
        name="like_comment_toggle",
    ),
    # htmx detail page(thread and reply)
    path("<str:username>/threads/<int:id>/", views.get_thread, name="get_thread"),
    path("<str:username>/replies/<int:id>/", views.get_reply, name="get_reply"),
    # htmx repost threads or comments
    path(
        "repost-toggle/thread/<int:id>/",
        views.repost_thread_toggle,
        name="repost_thread_toggle",
    ),
    path(
        "repost-toggle/comment/<int:id>/",
        views.repost_comment_toggle,
        name="repost_comment_toggle",
    ),
    # htmx get likes
    path(
        "<str:username>/threads-likes/<int:id>/",
        views.get_thread_likes,
        name="get_thread_likes",
    ),
    path(
        "<str:username>/replies-likes/<int:id>/",
        views.get_reply_likes,
        name="get_reply_likes",
    ),
    # notification htmx
    path("notification/", views.notification, name="notification"),
    path("check-reddot/", views.check_reddot, name="check_reddot"),
]

thread/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q


from .models import (
    Thread,
    Comment,
    Like,
    LikeComment,
    Repost,
    RepostComment,
    Follow,
    Notification,
)
from .utils import (
    create_thread_post,
    create_thread_images,
    create_cmt,
    create_cmt_images,
)


@login_required
def home(request):
    return redirect("thread:feed")


@login_required
def feed(request):
    threads = Thread.objects.all()
    paginator = Paginator(threads, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"threads": page_obj, "following": False}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(request, "thread/partials/_more_feed.html", context)
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "thread/partials/_feed.html", context)
    return render(request, "thread/f_feed.html", context)


@login_required
def following_feed(request):
    following = request.user.following.all()
    # Create a list of user IDs of the users that the authenticated user is following
    following_user_ids = [follow.followed.id for follow in following]

    # Use Q objects to construct an OR query to filter threads
    threads_of_following_users = Thread.objects.filter(
        Q(user__id__in=following_user_ids)
    ).distinct()

    paginator = Paginator(threads_of_following_users, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"threads": page_obj, "following": True}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(request, "thread/partials/_more_feed.html", context)
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "thread/partials/_feed.html", context)
    return render(request, "thread/f_feed.html", context)


@login_required
def create_thread(request):
    if request.method == "POST":
        content_list = request.POST.getlist("content")
        image_count_list = request.POST.getlist("image_count")
        image_list = request.FILES.getlist("thread_images")

        # Ensure thred content and thread images are not both empty.
        if len(content_list[0]) == 0 and int(image_count_list[0]) == 0:
            messages.warning(
                request, "You have to provide some content to create thread."
            )
            return redirect("thread:feed")
        # One unit case, just create a thread
        if len(content_list) == 1:
            # create thread
            thread = create_thread_post(content_list[0], request.user)
            create_thread_images(image_list, thread)
        # Two unit case, create thread and create comment
        if len(content_list) == 2:
            # create thread
            thread = create_thread_post(content_list[0], request.user)
            right = int(image_count_list[0])
            create_thread_images(image_list[:right], thread)
            # create comment
            comment = create_cmt(content_list[1], request.user, thread)
            left = int(image_count_list[0])
            right = left + int(image_count_list[1])
            create_cmt_images(image_list[left:right], comment)
        # More thatn two units, create thread, comment and child cmts
        if len(content_list) > 2:
            # create thread
            thread = create_thread_post(content_list[0], request.user)
            right = int(image_count_list[0])
            create_thread_images(image_list[:right], thread)
            # create parent comment
            comment = create_cmt(content_list[1], request.user, thread)
            left = int(image_count_list[0])
            right = left + int(image_count_list[1])
            create_cmt_images(image_list[left:right], comment)
            # create child comments
            i = 2
            while i < len(content_list):
                child_cmt = create_cmt(
                    content_list[i], request.user, thread, parent_comment=comment
                )
                left = 0
                for j in range(i):
                    left += int(image_count_list[j])
                right = left + int(image_count_list[i])
                create_cmt_images(image_list[left:right], comment=child_cmt)
                i += 1

        messages.success(request, "Thread created successfully.")
        return redirect("thread:feed")
    else:
        return redirect("thread:feed")


@login_required
def get_thread_form_unit(request):
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "partials/htmx/_thread_form_unit.html")
    return redirect("thread:feed")


@login_required
def get_thread_reply_form(request, id):
    if request.META.get("HTTP_HX_REQUEST"):
        thread = get_object_or_404(Thread, pk=id)
        context = {"thread": thread}
        return render(request, "partials/htmx/_thread_reply_form.html", context)
    return redirect("thread:feed")


@login_required
def get_comment_reply_form(request, id):
    if request.META.get("HTTP_HX_REQUEST"):
        comment = get_object_or_404(Comment, pk=id)
        context = {"comment": comment}
        return render(request, "partials/htmx/_comment_reply_form.html", context)
    return redirect("thread:feed")


@login_required
def get_reply_form_unit(request):
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "partials/htmx/_reply_form_unit.html")
    return redirect("thread:feed")


@login_required
def create_reply(request):
    if request.method == "POST":
        content_list = request.POST.getlist("content")
        image_count_list = request.POST.getlist("image_count")
        image_list = request.FILES.getlist("reply_images")
        thread_id = request.POST.get("thread_id")
        comment_id = request.POST.get("comment_id")

        thread = get_object_or_404(Thread, pk=thread_id)
        parent_comment = None
        if comment_id:
            parent_comment = get_object_or_404(Comment, pk=comment_id)

        # Ensure thred content and thread images are not both empty.
        if len(content_list[0]) == 0 and int(image_count_list[0]) == 0:
            messages.warning(
                request, "You have to provide some content to create reply."
            )
            return redirect("thread:feed")
        # One comment case
        cmt = create_cmt(
            content=content_list[0],
            user=request.user,
            thread=thread,
            parent_comment=parent_comment,
        )
        create_cmt_images(
            image_list=image_list[: int(image_count_list[0])], comment=cmt
        )
        # More than one comment case
        if len(content_list) > 1:
            i = 1
            while i < len(content_list):
                child_cmt = create_cmt(
                    content=content_list[i],
                    user=request.user,
                    thread=thread,
                    parent_comment=cmt,
                )
                left = 0
                for j in range(i):
                    left += int(image_count_list[j])
                right = left + int(image_count_list[i])
                create_cmt_images(image_list=image_list[left:right], comment=child_cmt)
                i += 1

        messages.success(request, "Reply created successfully.")

        if parent_comment:
            return redirect(
                "thread:get_reply",
                username=parent_comment.user.username,
                id=int(comment_id),
            )
        else:
            return redirect(
                "thread:get_thread", username=thread.user.username, id=int(thread_id)
            )

    return redirect("thread:feed")


@login_required
def get_thread(request, username, id):
    thread = get_object_or_404(Thread, pk=id)
    direct_comments = Comment.objects.filter(thread=thread, parent_comment=None)

    paginator = Paginator(direct_comments, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"thread": thread, "direct_comments": page_obj}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(
            request,
            "thread/htmx/partials/_more_comment_section_for_thread_page.html",
            context,
        )
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "thread/htmx/thread_page.html", context)
    return render(request, "thread/f_thread_page.html", context)


@login_required
def get_reply(request, username, id):
    comment = get_object_or_404(Comment, pk=id)
    sub_comments = Comment.objects.filter(parent_comment=comment, thread=comment.thread)

    paginator = Paginator(sub_comments, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"comment": comment, "sub_comments": page_obj}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(
            request,

thread/templates/thread/htmx/partials/_avatar.html
{% load static %}
{% load extra %}
{% load thumbnail %}
<!-- Avatar -->
<a href="{% url 'accounts:profile' u.username %}" class="relative h-fit">
    {% if u.myuser.profile_picture %}
        <div className="avatar">
            <div>
                {% thumbnail u.myuser.profile_picture '70' as im %}
                    <img src="{{ im.url }}"
                         srcset="{% thumbnail u.myuser.profile_picture '50' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %}"
                         alt="Profile picture of {{ u.username }}"
                         sizes="100vw"
                         width="{{ im.width }}"
                         height="{{ im.height }}"
                         class="w-12 h-12 rounded-full" />
                {% endthumbnail %}
            </div>
        </div>
    {% else %}
        <div class="avatar placeholder">
            <div class="bg-neutral-focus text-neutral-content rounded-full w-12">
                <span>{{ u.username|ecut }}</span>
            </div>
        </div>
    {% endif %}
    {% if show_heart %}
        <div class="bg-red-600 p-1 text-white border-white border-2 rounded-full absolute left-7 -bottom-2">
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 20 20"
                 fill="currentColor"
                 class="w-4 h-4">
                <path d="M9.653 16.915l-.005-.003-.019-.01a20.759 20.759 0 01-1.162-.682 22.045 22.045 0 01-2.582-1.9C4.045 12.733 2 10.352 2 7.5a4.5 4.5 0 018-2.828A4.5 4.5 0 0118 7.5c0 2.852-2.044 5.233-3.885 6.82a22.049 22.049 0 01-3.744 2.582l-.019.01-.005.003h-.002a.739.739 0 01-.69.001l-.002-.001z" />
            </svg>
        </div>
    {% endif %}
</a>
<!-- usernames -->
<div class="flex-grow flex items-center border-b-[1px] border-gray-200 pb-4">
    <a href="{% url 'accounts:profile' u.username %}" class="flex-grow">
        <div class="font-semibold hover:underline">{{ u.username }}</div>
        <div class="text-neutral-content">{{ u.first_name }} {{ u.last_name }}</div>
        {% if show_follower %}
            <div class="mt-2">{{ u.followers.all.count|format_kay }} follower{{ u.followers.all.count|pluralize }}</div>
        {% endif %}
    </a>
    {% if not u == user %}
        <div {% if u.is_followed_by_authenticated_user %} x-data="{text: 'Following'}" {% else %} x-data="{text: 'Follow'}" {% endif %}
             x-text="text"
             @click="text == 'Following' ? text = 'Follow' : text = 'Following'"
             :class="text == 'Following' ? 'text-gray-400' : ''"
             hx-post="{% url 'accounts:follow_toggle' u.id %}"
             hx-swap="none"
             class="py-1 px-4 bg-white border border-gray-200 h-fit rounded-md font-bold"></div>
    {% endif %}
</div>

thread/templates/thread/htmx/partials/_comment.html
{% load extra %}
<!-- Comment -->
<div class="w-full px-2 sm:px-4 text-base sm:text-lg mt-3">
    <!-- Profile and name -->
    <div class="flex items-center space-x-3 mb-2">
        {% include "partials/components/_profile_picture.html" with u=comment.user %}
        <div class="flex justify-between py-1 w-full">
            <a class="font-semibold text-black cursor-pointer"
               href="{% url 'accounts:profile' comment.user.username %}">{{ comment.user.username }}</a>
            <div class="flex items-center space-x-2 sm:pr-2">
                <span class="text-neutral-content">{{ comment.created_at|time_ago }}</span>
                <span class="cursor-pointer">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM12.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM18.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
                    </svg>
                </span>
            </div>
        </div>
    </div>
    <!-- Comment Content -->
    <div class="w-full">
        <p class="text-base-content font-extralight">{{ comment.content }}</p>
        <!-- Image content if any -->
        {% if comment.comment_image.all %}
            {% include "accounts/partials/_comment_carousel.html" with cmt=comment %}
        {% endif %}
        <!-- Action btns -->
        {% include "thread/partials/_comment_actions.html" with  cmt=comment %}
        <!-- Replys and likes-->
        <div class="flex text-neutral-content pt-2 space-x-2">
            {% if comment.comment_count > 0 %}
                <span class="cursor-pointer hover:underline">{{ comment.comment_count }}
                    {% if comment.comment_count > 1 %}
                        replies
                    {% else %}
                        reply
                    {% endif %}
                </span>
                <span>.</span>
            {% endif %}
            {% if comment.likes_count > 0 %}
                <span hx-get="{% url 'thread:get_reply_likes' comment.user.username cmt.id %}"  hx-indicator="#likes-indicator" hx-target="#likes-users-container" onclick="likes_modal.showModal()" class="cursor-pointer hover:underline" x-data="{ lc: {{ comment.likes_count }}, lcc: ' like{{ comment.likes_count|pluralize }}' }" x-text="lc + lcc" @toggle-like-cmt-{{ cmt.id }}.window="$event.detail.red ? lc -= 1 : lc += 1"></span>
            {% else %}
                <span x-data="{ lc: {{ comment.likes_count }}, lcc: ' like{{ comment.likes_count|pluralize }}' }" x-text="lc + lcc" @toggle-like-cmt-{{ comment.id }}.window="$event.detail.red ? lc -= 1 : lc += 1"></span>
            {% endif %}
        </div>
    </div>
</div>

thread/templates/thread/htmx/partials/_comment_of_comment_section.html
{% load extra %}
<!-- Comment of comment section below thread -->
<div class="w-full flex px-2 sm:px-4 space-x-2 sm:space-x-4 text-base sm:text-lg">
    <!-- Left -->
    <div class="flex flex-col items-center">
        {% include "partials/components/_profile_picture.html" with u=cmt.user %}
        {% if cmt.comment_count > 0 %}
            <div class="bg-neutral-content w-[2px] grow my-3 z-10"></div>
            {% if cmt.comment_count == 1 %}
                {% include "partials/components/_one_small_profile.html" with user=cmt.sub_comment.first.user %}
            {% elif cmt.comment_count > 1 %}
                {% include "partials/components/_two_small_profile.html" with cmts=cmt.sub_comment.all %}
            {% endif %}
        {% endif %}
    </div>
    <!-- Right -->
    <div class="w-full">
        <!-- Right first row-->
        <div class="flex justify-between py-1">
            <a class="font-semibold text-black cursor-pointer"
               href="{% url 'accounts:profile' cmt.user.username %}">{{ cmt.user.username }}</a>
            <div class="flex items-center space-x-2 sm:pr-2">
                <span class="text-neutral-content">{{ cmt.created_at|time_ago }}</span>
                <span class="cursor-pointer">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM12.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM18.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
                    </svg>
                </span>
            </div>
        </div>
        <!-- Right text content -->
        <p class="text-base-content font-extralight cursor-pointer"
           hx-target="#container"
           hx-indicator="#indicator"
           hx-push-url="true"
           hx-trigger="click"
           hx-swap="innerHTML"
           hx-get="{% url 'thread:get_reply' username=cmt.user.username id=cmt.id %}">{{ cmt.content }}</p>
        <!-- Right Image content if any -->
        {% if cmt.comment_image.all %}
            {% include "accounts/partials/_comment_carousel.html" with cmt=cmt %}
        {% endif %}
        <!-- Action btns -->
        {% include "thread/partials/_comment_actions.html" with cmt=cmt %}
        <!-- Replys and likes-->
        <div class="flex text-neutral-content pt-2 space-x-2">
            {% if cmt.comment_count > 0 %}
                <span class="cursor-pointer hover:underline"
                      hx-target="#container"
                      hx-indicator="#indicator"
                      hx-push-url="true"
                      hx-trigger="click"
                      hx-swap="innerHTML"
                      hx-get="{% url 'thread:get_reply' username=cmt.user.username id=cmt.id %}">{{ cmt.comment_count }}
                    {% if cmt.comment_count > 1 %}
                        replies
                    {% else %}
                        reply
                    {% endif %}
                </span>
                <span>.</span>
            {% endif %}
            {% if cmt.likes_count > 0 %}
                <span hx-get="{% url 'thread:get_reply_likes' cmt.user.username cmt.id %}"  hx-indicator="#likes-indicator" hx-target="#likes-users-container" onclick="likes_modal.showModal()" class="cursor-pointer hover:underline" x-data="{ lc: {{ cmt.likes_count }}, lcc: ' like{{ cmt.likes_count|pluralize }}' }" x-text="lc + lcc" @toggle-like-cmt-{{ cmt.id }}.window="$event.detail.red ? lc -= 1 : lc += 1"></span>
            {% else %}
                <span x-data="{ lc: {{ cmt.likes_count }}, lcc: ' like{{ cmt.likes_count|pluralize }}' }" x-text="lc + lcc" @toggle-like-cmt-{{ cmt.id }}.window="$event.detail.red ? lc -= 1 : lc += 1"></span>
            {% endif %}
        </div>
    </div>
</div>

thread/templates/thread/htmx/partials/_h_comment.html
{% load extra %}
<!--Hierarchy Comment -->
<div class="w-full flex px-2 sm:px-4 space-x-2 sm:space-x-4 text-base sm:text-lg">
    <!-- Left -->
    <div class="flex flex-col items-center">
        {% include "partials/components/_profile_picture.html" with u=cmt.user %}
        <div class="bg-neutral-content w-[2px] grow relative my-3 z-10">
            {% if cmt.comment_count > 1 %}
                {% include "partials/components/_circle.html" %}
            {% endif %}
        </div>
    </div>
    <!-- Right -->
    <div class="w-full">
        <!-- Right first row-->
        <div class="flex justify-between py-1">
            <a class="font-semibold text-black cursor-pointer"
               href="{% url 'accounts:profile' cmt.user.username %}">{{ cmt.user.username }}</a>
            <div class="flex items-center space-x-2 sm:pr-2">
                <span class="text-neutral-content">{{ cmt.created_at|time_ago }}</span>
                <span class="cursor-pointer">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM12.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM18.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
                    </svg>
                </span>
            </div>
        </div>
        <!-- Right text content -->
        <p class="text-base-content font-extralight cursor-pointer"
           hx-target="#container"
           hx-indicator="#indicator"
           hx-push-url="true"
           hx-trigger="click"
           hx-get="{% url 'thread:get_reply' username=cmt.user.username id=cmt.id %}">{{ cmt.content }}</p>
        <!-- Right Image content if any -->
        {% if cmt.comment_image.all %}
            {% include "accounts/partials/_comment_carousel.html" with cmt=cmt %}
        {% endif %}
        <!-- Action btns -->
        {% include "thread/partials/_comment_actions.html" with  cmt=cmt %}
        <!-- Replys and likes-->
        <div class="flex text-neutral-content pt-2 space-x-2">
            {% if cmt.comment_count > 0 %}
                <span class="cursor-pointer hover:underline"
                      hx-target="#container"
                      hx-indicator="#indicator"
                      hx-push-url="true"
                      hx-trigger="click"
                      hx-get="{% url 'thread:get_reply' username=cmt.user.username id=cmt.id %}">{{ cmt.comment_count }}
                    {% if cmt.comment_count > 1 %}
                        replies
                    {% else %}
                        reply
                    {% endif %}
                </span>
                <span>.</span>
            {% endif %}
            {% if cmt.likes_count > 0 %}
                <span hx-get="{% url 'thread:get_reply_likes' cmt.user.username cmt.id %}"  hx-indicator="#likes-indicator" hx-target="#likes-users-container" onclick="likes_modal.showModal()" class="cursor-pointer hover:underline" x-data="{ lc: {{ cmt.likes_count }}, lcc: ' like{{ cmt.likes_count|pluralize }}' }" x-text="lc + lcc" @toggle-like-cmt-{{ cmt.id }}.window="$event.detail.red ? lc -= 1 : lc += 1"></span>
            {% else %}
                <span x-data="{ lc: {{ cmt.likes_count }}, lcc: ' like{{ cmt.likes_count|pluralize }}' }" x-text="lc + lcc" @toggle-like-cmt-{{ cmt.id }}.window="$event.detail.red ? lc -= 1 : lc += 1"></span>
            {% endif %}
        </div>
    </div>
</div>

thread/templates/thread/htmx/partials/_more_comment_section.html
{% for cmt in direct_comments %}
    <div class="divider my-0"></div>
    {% if forloop.last and direct_comments.next_page_number %}
        <div hx-get="{% url 'thread:get_thread' cmt.thread.user.username cmt.thread.id %}?page={{ direct_comments.next_page_number }}"
             hx-trigger="revealed"
             hx-indicator="#more-comment-section-indicator"
             hx-swap="afterend">
            {% include "thread/htmx/partials/_comment_of_comment_section.html" with cmt=cmt %}
        </div>
    {% elif forloop.last %}
        <div>{% include "thread/htmx/partials/_comment_of_comment_section.html" with cmt=cmt %}</div>
    {% else %}
        <div>{% include "thread/htmx/partials/_comment_of_comment_section.html" with cmt=cmt %}</div>
    {% endif %}
{% endfor %}

thread/templates/thread/htmx/partials/_more_search.html
{% for u in page_obj %}
    {% if not u == user %}
        {% if forloop.last and page_obj.next_page_number %}
            <div class="flex pt-4 space-x-3 cursor-pointer"
                 hx-get="{% url 'thread:search' %}?page={{ page_obj.next_page_number }}"
                 hx-trigger="intersect once"
                 hx-indicator="#more-search-indicator"
                 hx-sync="#search:abort"
                 hx-swap="afterend">{% include "thread/htmx/partials/_avatar.html" with u=u show_follower=True %}</div>
        {% elif forloop.last %}
            <div class="flex pt-4 space-x-3 cursor-pointer">
                {% include "thread/htmx/partials/_avatar.html" with u=u show_follower=True %}
            </div>
            <div class="text-center">That's all.</div>
        {% else %}
            <div class="flex pt-4 space-x-3 cursor-pointer">
                {% include "thread/htmx/partials/_avatar.html" with u=u show_follower=True %}
            </div>
        {% endif %}
    {% elif u == user and forloop.last %}
        <div class="text-center">That's all.</div>
    {% endif %}
{% empty %}
    <dir>No profiles found.</dir>
{% endfor %}