accounts/urls.py
from django.urls import path
from .views import (
    register_view,
    login_view,
    logout_view,
    profile_view,
    profile_threads,
    profile_replies,
    profile_reposts,
    follow_toggle,
    profile_followers,
    profile_following,
    profile_edit,
)

app_name = "accounts"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", register_view, name="register"),
    path("profile/<str:username>/", profile_view, name="profile"),
    path("profile/<str:username>/threads/", profile_threads, name="profile_threads"),
    path("profile/<str:username>/replies/", profile_replies, name="profile_replies"),
    path("profile/<str:username>/reposts/", profile_reposts, name="profile_reposts"),
    # htmx follow toggle
    path(
        "follow-toggle/profile/<int:id>/",
        follow_toggle,
        name="follow_toggle",
    ),
    # htmx followers and followings get
    path(
        "profile/<str:username>/followers/", profile_followers, name="profile_followers"
    ),
    path(
        "profile/<str:username>/following/", profile_following, name="profile_following"
    ),
    # edit profile
    path("profile/<int:id>/edit/", profile_edit, name="profile_edit"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("thread.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thread/urls.py
from django.urls import path
from . import views


app_name = "thread"

urlpatterns = [
    path("", views.home, name="home"),
    path("feed/", views.feed, name="feed"),
    path("following-feed/", views.following_feed, name="following_feed"),
    path("search/", views.search, name="search"),
    path("search-query/", views.search_query, name="search_query"),
    path("create-thread/", views.create_thread, name="create_thread"),
    path("create-reply/", views.create_reply, name="create_reply"),
    # htmx form related (thread and comment)
    path(
        "thread-reply-form/<int:id>/",
        views.get_thread_reply_form,
        name="get_thread_reply_form",
    ),
    path(
        "comment-reply-form/<int:id>/",
        views.get_comment_reply_form,
        name="get_comment_reply_form",
    ),
    path("thread-form-unit/", views.get_thread_form_unit, name="get_thread_form_unit"),
    path("reply-form-unit/", views.get_reply_form_unit, name="get_reply_form_unit"),
    # htmx like features related routes
    path(
        "like-toggle/thread/<int:id>/",
        views.like_thread_toggle,
        name="like_thread_toggle",
    ),
    path(
        "like-toggle/comment/<int:id>/",
        views.like_comment_toggle,
        name="like_comment_toggle",
    ),
    # htmx detail page(thread and reply)
    path("<str:username>/threads/<int:id>/", views.get_thread, name="get_thread"),
    path("<str:username>/replies/<int:id>/", views.get_reply, name="get_reply"),
    # htmx repost threads or comments
    path(
        "repost-toggle/thread/<int:id>/",
        views.repost_thread_toggle,
        name="repost_thread_toggle",
    ),
    path(
        "repost-toggle/comment/<int:id>/",
        views.repost_comment_toggle,
        name="repost_comment_toggle",
    ),
    # htmx get likes
    path(
        "<str:username>/threads-likes/<int:id>/",
        views.get_thread_likes,
        name="get_thread_likes",
    ),
    path(
        "<str:username>/replies-likes/<int:id>/",
        views.get_reply_likes,
        name="get_reply_likes",
    ),
    # notification htmx
    path("notification/", views.notification, name="notification"),
    path("check-reddot/", views.check_reddot, name="check_reddot"),
]

thread/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q


from .models import (
    Thread,
    Comment,
    Like,
    LikeComment,
    Repost,
    RepostComment,
    Follow,
    Notification,
)
from .utils import (
    create_thread_post,
    create_thread_images,
    create_cmt,
    create_cmt_images,
)


@login_required
def home(request):
    return redirect("thread:feed")


@login_required
def feed(request):
    threads = Thread.objects.all()
    paginator = Paginator(threads, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"threads": page_obj, "following": False}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(request, "thread/partials/_more_feed.html", context)
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "thread/partials/_feed.html", context)
    return render(request, "thread/f_feed.html", context)


@login_required
def following_feed(request):
    following = request.user.following.all()
    # Create a list of user IDs of the users that the authenticated user is following
    following_user_ids = [follow.followed.id for follow in following]

    # Use Q objects to construct an OR query to filter threads
    threads_of_following_users = Thread.objects.filter(
        Q(user__id__in=following_user_ids)
    ).distinct()

    paginator = Paginator(threads_of_following_users, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"threads": page_obj, "following": True}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(request, "thread/partials/_more_feed.html", context)
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "thread/partials/_feed.html", context)
    return render(request, "thread/f_feed.html", context)


@login_required
def create_thread(request):
    if request.method == "POST":
        content_list = request.POST.getlist("content")
        image_count_list = request.POST.getlist("image_count")
        image_list = request.FILES.getlist("thread_images")

        # Ensure thred content and thread images are not both empty.
        if len(content_list[0]) == 0 and int(image_count_list[0]) == 0:
            messages.warning(
                request, "You have to provide some content to create thread."
            )
            return redirect("thread:feed")
        # One unit case, just create a thread
        if len(content_list) == 1:
            # create thread
            thread = create_thread_post(content_list[0], request.user)
            create_thread_images(image_list, thread)
        # Two unit case, create thread and create comment
        if len(content_list) == 2:
            # create thread
            thread = create_thread_post(content_list[0], request.user)
            right = int(image_count_list[0])
            create_thread_images(image_list[:right], thread)
            # create comment
            comment = create_cmt(content_list[1], request.user, thread)
            left = int(image_count_list[0])
            right = left + int(image_count_list[1])
            create_cmt_images(image_list[left:right], comment)
        # More thatn two units, create thread, comment and child cmts
        if len(content_list) > 2:
            # create thread
            thread = create_thread_post(content_list[0], request.user)
            right = int(image_count_list[0])
            create_thread_images(image_list[:right], thread)
            # create parent comment
            comment = create_cmt(content_list[1], request.user, thread)
            left = int(image_count_list[0])
            right = left + int(image_count_list[1])
            create_cmt_images(image_list[left:right], comment)
            # create child comments
            i = 2
            while i < len(content_list):
                child_cmt = create_cmt(
                    content_list[i], request.user, thread, parent_comment=comment
                )
                left = 0
                for j in range(i):
                    left += int(image_count_list[j])
                right = left + int(image_count_list[i])
                create_cmt_images(image_list[left:right], comment=child_cmt)
                i += 1

        messages.success(request, "Thread created successfully.")
        return redirect("thread:feed")
    else:
        return redirect("thread:feed")


@login_required
def get_thread_form_unit(request):
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "partials/htmx/_thread_form_unit.html")
    return redirect("thread:feed")


@login_required
def get_thread_reply_form(request, id):
    if request.META.get("HTTP_HX_REQUEST"):
        thread = get_object_or_404(Thread, pk=id)
        context = {"thread": thread}
        return render(request, "partials/htmx/_thread_reply_form.html", context)
    return redirect("thread:feed")


@login_required
def get_comment_reply_form(request, id):
    if request.META.get("HTTP_HX_REQUEST"):
        comment = get_object_or_404(Comment, pk=id)
        context = {"comment": comment}
        return render(request, "partials/htmx/_comment_reply_form.html", context)
    return redirect("thread:feed")


@login_required
def get_reply_form_unit(request):
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "partials/htmx/_reply_form_unit.html")
    return redirect("thread:feed")


@login_required
def create_reply(request):
    if request.method == "POST":
        content_list = request.POST.getlist("content")
        image_count_list = request.POST.getlist("image_count")
        image_list = request.FILES.getlist("reply_images")
        thread_id = request.POST.get("thread_id")
        comment_id = request.POST.get("comment_id")

        thread = get_object_or_404(Thread, pk=thread_id)
        parent_comment = None
        if comment_id:
            parent_comment = get_object_or_404(Comment, pk=comment_id)

        # Ensure thred content and thread images are not both empty.
        if len(content_list[0]) == 0 and int(image_count_list[0]) == 0:
            messages.warning(
                request, "You have to provide some content to create reply."
            )
            return redirect("thread:feed")
        # One comment case
        cmt = create_cmt(
            content=content_list[0],
            user=request.user,
            thread=thread,
            parent_comment=parent_comment,
        )
        create_cmt_images(
            image_list=image_list[: int(image_count_list[0])], comment=cmt
        )
        # More than one comment case
        if len(content_list) > 1:
            i = 1
            while i < len(content_list):
                child_cmt = create_cmt(
                    content=content_list[i],
                    user=request.user,
                    thread=thread,
                    parent_comment=cmt,
                )
                left = 0
                for j in range(i):
                    left += int(image_count_list[j])
                right = left + int(image_count_list[i])
                create_cmt_images(image_list=image_list[left:right], comment=child_cmt)
                i += 1

        messages.success(request, "Reply created successfully.")

        if parent_comment:
            return redirect(
                "thread:get_reply",
                username=parent_comment.user.username,
                id=int(comment_id),
            )
        else:
            return redirect(
                "thread:get_thread", username=thread.user.username, id=int(thread_id)
            )

    return redirect("thread:feed")


@login_required
def get_thread(request, username, id):
    thread = get_object_or_404(Thread, pk=id)
    direct_comments = Comment.objects.filter(thread=thread, parent_comment=None)

    paginator = Paginator(direct_comments, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"thread": thread, "direct_comments": page_obj}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(
            request,
            "thread/htmx/partials/_more_comment_section_for_thread_page.html",
            context,
        )
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "thread/htmx/thread_page.html", context)
    return render(request, "thread/f_thread_page.html", context)


@login_required
def get_reply(request, username, id):
    comment = get_object_or_404(Comment, pk=id)
    sub_comments = Comment.objects.filter(parent_comment=comment, thread=comment.thread)

    paginator = Paginator(sub_comments, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"comment": comment, "sub_comments": page_obj}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(
            request,

thread/templates/thread/partials/_comment_actions.html
<div class="flex text-black" x-data>
    <div class="cursor-pointer p-2 rounded-full hover:bg-gray-400/10 like-comment"
         {% if cmt in user.liked_comments.all %}x-data="{ red: true }" {% else %} x-data="{ red: false}" {% endif %}
         :class="red ? 'text-red-600' : ''"
         @click="$dispatch('toggle-like-cmt-{{ cmt.id }}', {red: red}); red = !red"
         hx-post="{% url 'thread:like_comment_toggle' cmt.id %}"
         hx-swap="none"
         hx-trigger="click">
        <svg xmlns="http://www.w3.org/2000/svg"
             x-bind:fill="red ? 'currentColor' : 'none'"
             viewBox="0 0 24 24"
             stroke-width="1.5"
             stroke="currentColor"
             class="w-6 h-6 sm:w-8 sm:h-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
        </svg>
    </div>
    <div class="cursor-pointer p-2 rounded-full hover:bg-gray-400/10 reply-action"
         hx-get="{% url 'thread:get_comment_reply_form' id=cmt.id %}"
         hx-indicator="#reply-indicator"
         hx-target="#reply-container">
        <svg xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 24 24"
             stroke-width="1.5"
             stroke="currentColor"
             class="w-6 h-6 sm:w-8 sm:h-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 01-.923 1.785A5.969 5.969 0 006 21c1.282 0 2.47-.402 3.445-1.087.81.22 1.668.337 2.555.337z" />
        </svg>
    </div>
    <!-- Repost and Unrepost -->
    <div {% if cmt in user.reposted_comments.all %} x-data="{reposted: true}" {% else %} x-data="{reposted: false}" {% endif %}
         @click="reposted = !reposted"
         hx-post="{% url 'thread:repost_comment_toggle' cmt.id %}"
         hx-target="#messages"
         class="cursor-pointer p-2 rounded-full hover:bg-gray-400/10">
        <svg x-show="reposted"
             xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 24 24"
             stroke-width="1.5"
             stroke="currentColor"
             class="w-6 h-6 sm:w-8 sm:h-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <svg x-show="!reposted"
             xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 24 24"
             stroke-width="1.5"
             stroke="currentColor"
             class="w-6 h-6 sm:w-8 sm:h-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12c0-1.232-.046-2.453-.138-3.662a4.006 4.006 0 00-3.7-3.7 48.678 48.678 0 00-7.324 0 4.006 4.006 0 00-3.7 3.7c-.017.22-.032.441-.046.662M19.5 12l3-3m-3 3l-3-3m-12 3c0 1.232.046 2.453.138 3.662a4.006 4.006 0 003.7 3.7 48.656 48.656 0 007.324 0 4.006 4.006 0 003.7-3.7c.017-.22.032-.441.046-.662M4.5 12l3 3m-3-3l-3 3" />
        </svg>
    </div>
    <!-- Copy to clipboard -->
    <div @click="navigator.clipboard.writeText('{{ request.META.HTTP_HOST }}{% url 'thread:get_reply' cmt.user.username cmt.id %}');"
         class="copy-to-clipboard cursor-pointer p-2 rounded-full hover:bg-gray-400/10">
        <svg xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 24 24"
             stroke-width="1.5"
             stroke="currentColor"
             class="w-6 h-6 sm:w-8 sm:h-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
        </svg>
    </div>
</div>

thread/templates/thread/partials/_more_feed.html
<!-- More Feed -->
{% for thread in threads %}
    {% if forloop.last and threads.next_page_number %}
        <div class="last-feed-item"
             {% if following %} hx-get="{% url 'thread:following_feed' %}?page={{ threads.next_page_number }}" {% else %} hx-get="{% url 'thread:feed' %}?page={{ threads.next_page_number }}" {% endif %}
             hx-trigger="intersect once"
             hx-indicator="#feed-indicator"
             hx-swap="afterend">{% include "thread/partials/_thread.html" with thread=thread %}</div>
    {% elif forloop.last %}
        <div>{% include "thread/partials/_thread.html" with thread=thread %}</div>
    {% else %}
        <div>{% include "thread/partials/_thread.html" with thread=thread %}</div>
    {% endif %}
{% empty %}
    <div class="h-96 flex justify-center items-center">There is no feed yet.</div>
{% endfor %}

thread/templates/thread/partials/_more_notification.html
{% for n in notifications %}
    {% if forloop.last and notifications.next_page_number %}
        <div class="flex pt-4 space-x-3 cursor-pointer"
             hx-get="{% url 'thread:notification' %}?page={{ notifications.next_page_number }}"
             hx-trigger="intersect once"
             hx-indicator="#more-notification-indicator"
             hx-swap="afterend">{% include "thread/htmx/partials/_noti.html" with n=n %}</div>
    {% else %}
        <div class="flex pt-4 space-x-3 cursor-pointer">{% include "thread/htmx/partials/_noti.html" with n=n %}</div>
    {% endif %}
{% endfor %}

thread/templates/thread/partials/_thread.html
{% load extra %}
<!-- Thread Post -->
<div class="w-full flex px-2 sm:px-4 space-x-2 sm:space-x-4 text-base sm:text-lg">
    <!-- Left -->
    <div class="flex flex-col items-center">
        {% include "partials/components/_profile_picture.html" with u=thread.user %}
        {% if thread.comment_count > 0 %}
            <div class="bg-neutral-content w-[2px] grow my-3 z-10"></div>
            {% if thread.comment_count == 1 %}
                {% include "partials/components/_one_small_profile.html" with user=thread.comment.first.user %}
            {% elif thread.comment_count == 2 %}
                {% include "partials/components/_two_small_profile.html" with cmts=thread.comment.all %}
            {% elif thread.comment_count > 2 %}
                {% include "partials/components/_three_small_profile.html" with cmts=thread.comment.all %}
            {% endif %}
        {% endif %}
    </div>
    <!-- Right -->
    <div class="w-full">
        <!-- Right first row-->
        <div class="flex justify-between py-1">
            <a class="font-semibold text-black cursor-pointer"
               href="{% url 'accounts:profile' thread.user.username %}">{{ thread.user.username }}</a>
            <div class="flex items-center space-x-2 sm:pr-2">
                <span class="text-neutral-content">{{ thread.created_at|time_ago }}</span>
                <span class="cursor-pointer">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM12.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM18.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
                    </svg>
                </span>
            </div>
        </div>
        <!-- Right text content -->
        <p class="st text-base-content font-extralight cursor-pointer"
           hx-target="#container"
           hx-indicator="#indicator"
           hx-push-url="true"
           hx-trigger="click"
           hx-swap="innerHTML"
           hx-get="{% url 'thread:get_thread' username=thread.user.username id=thread.id %}">{{ thread.content }}</p>
        <!-- Right Image content if any -->
        {% if thread.image_thread.all %}
            {% include "thread/partials/_thread_carousel.html" with thread=thread %}
        {% endif %}
        <!-- Action btns -->
        {% include "thread/partials/_thread_actions.html" with thread=thread %}
        <!-- Replys and likes-->
        <div class="flex text-neutral-content pt-2 space-x-2">
            {% if thread.comment_count > 0 %}
                <span class="st cursor-pointer hover:underline"
                      hx-target="#container"
                      hx-indicator="#indicator"
                      hx-push-url="true"
                      hx-trigger="click"
                      hx-swap="innerHTML"
                      hx-get="{% url 'thread:get_thread' username=thread.user.username id=thread.id %}">
                    {{ thread.comment_count }}
                    {% if thread.comment_count > 1 %}
                        replies
                    {% else %}
                        reply
                    {% endif %}
                </span>
                <span>.</span>
            {% endif %}
            {% if thread.likes_count > 0 %}
                <span hx-get="{% url 'thread:get_thread_likes' thread.user.username thread.id %}"  hx-indicator="#likes-indicator" hx-target="#likes-users-container" onclick="likes_modal.showModal()" class="cursor-pointer hover:underline" x-data="{ lc: {{ thread.likes_count }}, lcc: ' like{{ thread.likes_count|pluralize }}' }" x-text="lc + lcc" @toggle-like-thread-{{ thread.id }}.window="$event.detail.red ? lc -= 1 : lc += 1"></span>
            {% else %}
                <span x-data="{ lc: {{ thread.likes_count }}, lcc: ' like{{ thread.likes_count|pluralize }}' }" x-text="lc + lcc" @toggle-like-thread-{{ thread.id }}.window="$event.detail.red ? lc -= 1 : lc += 1"></span>
            {% endif %}
        </div>
    </div>
</div>
<div class="divider"></div>

thread/templates/thread/partials/_thread_actions.html
<div class="flex text-black" x-data>
    <div class="cursor-pointer p-2 rounded-full hover:bg-gray-400/10 like-thread"
         {% if thread in user.liked_threads.all %} x-data="{ red: true }" {% else %} x-data="{ red: false}" {% endif %}
         :class="red ? 'text-red-600' : ''"
         hx-post="{% url 'thread:like_thread_toggle' thread.id %}"
         @click="$dispatch('toggle-like-thread-{{ thread.id }}', {red: red}); red = !red"
         hx-swap="none"
         hx-trigger="click">
        <svg xmlns="http://www.w3.org/2000/svg"
             x-bind:fill="red ? 'currentColor' : 'none'"
             viewBox="0 0 24 24"
             stroke-width="1.5"
             stroke="currentColor"
             class="w-6 h-6 sm:w-8 sm:h-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
        </svg>
    </div>
    <div class="cursor-pointer p-2 rounded-full hover:bg-gray-400/10 reply-action"
         hx-get="{% url 'thread:get_thread_reply_form' id=thread.id %}"
         hx-indicator="#reply-indicator"
         hx-target="#reply-container">
        <svg xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 24 24"
             stroke-width="1.5"
             stroke="currentColor"
             class="w-6 h-6 sm:w-8 sm:h-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 01-.923 1.785A5.969 5.969 0 006 21c1.282 0 2.47-.402 3.445-1.087.81.22 1.668.337 2.555.337z" />
        </svg>
    </div>
    <!-- Repost and Unrepost -->
    <div {% if thread in user.reposted_threads.all %} x-data="{reposted: true}" {% else %} x-data="{reposted: false}" {% endif %}
         @click="reposted = !reposted"
         hx-post="{% url 'thread:repost_thread_toggle' thread.id %}"
         hx-target="#messages"
         class="cursor-pointer p-2 rounded-full hover:bg-gray-400/10">
        <svg x-show="reposted"
             xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 24 24"
             stroke-width="1.5"
             stroke="currentColor"
             class="w-6 h-6 sm:w-8 sm:h-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <svg x-show="!reposted"
             xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 24 24"
             stroke-width="1.5"
             stroke="currentColor"
             class="w-6 h-6 sm:w-8 sm:h-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12c0-1.232-.046-2.453-.138-3.662a4.006 4.006 0 00-3.7-3.7 48.678 48.678 0 00-7.324 0 4.006 4.006 0 00-3.7 3.7c-.017.22-.032.441-.046.662M19.5 12l3-3m-3 3l-3-3m-12 3c0 1.232.046 2.453.138 3.662a4.006 4.006 0 003.7 3.7 48.656 48.656 0 007.324 0 4.006 4.006 0 003.7-3.7c.017-.22.032-.441.046-.662M4.5 12l3 3m-3-3l-3 3" />
        </svg>
    </div>
    <!-- Copy to clip board -->
    <div @click="navigator.clipboard.writeText('{{ request.META.HTTP_HOST }}{% url 'thread:get_thread' thread.user.username thread.id %}');"
         class="copy-to-clipboard cursor-pointer p-2 rounded-full hover:bg-gray-400/10">
        <svg xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 24 24"
             stroke-width="1.5"
             stroke="currentColor"
             class="w-6 h-6 sm:w-8 sm:h-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
        </svg>
    </div>
</div>