core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("thread.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thread/urls.py
from django.urls import path
from . import views


app_name = "thread"

urlpatterns = [
    path("", views.home, name="home"),
    path("feed/", views.feed, name="feed"),
    path("following-feed/", views.following_feed, name="following_feed"),
    path("search/", views.search, name="search"),
    path("search-query/", views.search_query, name="search_query"),
    path("create-thread/", views.create_thread, name="create_thread"),
    path("create-reply/", views.create_reply, name="create_reply"),
    # htmx form related (thread and comment)
    path(
        "thread-reply-form/<int:id>/",
        views.get_thread_reply_form,
        name="get_thread_reply_form",
    ),
    path(
        "comment-reply-form/<int:id>/",
        views.get_comment_reply_form,
        name="get_comment_reply_form",
    ),
    path("thread-form-unit/", views.get_thread_form_unit, name="get_thread_form_unit"),
    path("reply-form-unit/", views.get_reply_form_unit, name="get_reply_form_unit"),
    # htmx like features related routes
    path(
        "like-toggle/thread/<int:id>/",
        views.like_thread_toggle,
        name="like_thread_toggle",
    ),
    path(
        "like-toggle/comment/<int:id>/",
        views.like_comment_toggle,
        name="like_comment_toggle",
    ),
    # htmx detail page(thread and reply)
    path("<str:username>/threads/<int:id>/", views.get_thread, name="get_thread"),
    path("<str:username>/replies/<int:id>/", views.get_reply, name="get_reply"),
    # htmx repost threads or comments
    path(
        "repost-toggle/thread/<int:id>/",
        views.repost_thread_toggle,
        name="repost_thread_toggle",
    ),
    path(
        "repost-toggle/comment/<int:id>/",
        views.repost_comment_toggle,
        name="repost_comment_toggle",
    ),
    # htmx get likes
    path(
        "<str:username>/threads-likes/<int:id>/",
        views.get_thread_likes,
        name="get_thread_likes",
    ),
    path(
        "<str:username>/replies-likes/<int:id>/",
        views.get_reply_likes,
        name="get_reply_likes",
    ),
    # notification htmx
    path("notification/", views.notification, name="notification"),
    path("check-reddot/", views.check_reddot, name="check_reddot"),
]

thread/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q


from .models import (
    Thread,
    Comment,
    Like,
    LikeComment,
    Repost,
    RepostComment,
    Follow,
    Notification,
)
from .utils import (
    create_thread_post,
    create_thread_images,
    create_cmt,
    create_cmt_images,
)


@login_required
def home(request):
    return redirect("thread:feed")


@login_required
def feed(request):
    threads = Thread.objects.all()
    paginator = Paginator(threads, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"threads": page_obj, "following": False}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(request, "thread/partials/_more_feed.html", context)
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "thread/partials/_feed.html", context)
    return render(request, "thread/f_feed.html", context)


@login_required
def following_feed(request):
    following = request.user.following.all()
    # Create a list of user IDs of the users that the authenticated user is following
    following_user_ids = [follow.followed.id for follow in following]

    # Use Q objects to construct an OR query to filter threads
    threads_of_following_users = Thread.objects.filter(
        Q(user__id__in=following_user_ids)
    ).distinct()

    paginator = Paginator(threads_of_following_users, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"threads": page_obj, "following": True}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(request, "thread/partials/_more_feed.html", context)
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "thread/partials/_feed.html", context)
    return render(request, "thread/f_feed.html", context)


@login_required
def create_thread(request):
    if request.method == "POST":
        content_list = request.POST.getlist("content")
        image_count_list = request.POST.getlist("image_count")
        image_list = request.FILES.getlist("thread_images")

        # Ensure thred content and thread images are not both empty.
        if len(content_list[0]) == 0 and int(image_count_list[0]) == 0:
            messages.warning(
                request, "You have to provide some content to create thread."
            )
            return redirect("thread:feed")
        # One unit case, just create a thread
        if len(content_list) == 1:
            # create thread
            thread = create_thread_post(content_list[0], request.user)
            create_thread_images(image_list, thread)
        # Two unit case, create thread and create comment
        if len(content_list) == 2:
            # create thread
            thread = create_thread_post(content_list[0], request.user)
            right = int(image_count_list[0])
            create_thread_images(image_list[:right], thread)
            # create comment
            comment = create_cmt(content_list[1], request.user, thread)
            left = int(image_count_list[0])
            right = left + int(image_count_list[1])
            create_cmt_images(image_list[left:right], comment)
        # More thatn two units, create thread, comment and child cmts
        if len(content_list) > 2:
            # create thread
            thread = create_thread_post(content_list[0], request.user)
            right = int(image_count_list[0])
            create_thread_images(image_list[:right], thread)
            # create parent comment
            comment = create_cmt(content_list[1], request.user, thread)
            left = int(image_count_list[0])
            right = left + int(image_count_list[1])
            create_cmt_images(image_list[left:right], comment)
            # create child comments
            i = 2
            while i < len(content_list):
                child_cmt = create_cmt(
                    content_list[i], request.user, thread, parent_comment=comment
                )
                left = 0
                for j in range(i):
                    left += int(image_count_list[j])
                right = left + int(image_count_list[i])
                create_cmt_images(image_list[left:right], comment=child_cmt)
                i += 1

        messages.success(request, "Thread created successfully.")
        return redirect("thread:feed")
    else:
        return redirect("thread:feed")


@login_required
def get_thread_form_unit(request):
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "partials/htmx/_thread_form_unit.html")
    return redirect("thread:feed")


@login_required
def get_thread_reply_form(request, id):
    if request.META.get("HTTP_HX_REQUEST"):
        thread = get_object_or_404(Thread, pk=id)
        context = {"thread": thread}
        return render(request, "partials/htmx/_thread_reply_form.html", context)
    return redirect("thread:feed")


@login_required
def get_comment_reply_form(request, id):
    if request.META.get("HTTP_HX_REQUEST"):
        comment = get_object_or_404(Comment, pk=id)
        context = {"comment": comment}
        return render(request, "partials/htmx/_comment_reply_form.html", context)
    return redirect("thread:feed")


@login_required
def get_reply_form_unit(request):
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "partials/htmx/_reply_form_unit.html")
    return redirect("thread:feed")


@login_required
def create_reply(request):
    if request.method == "POST":
        content_list = request.POST.getlist("content")
        image_count_list = request.POST.getlist("image_count")
        image_list = request.FILES.getlist("reply_images")
        thread_id = request.POST.get("thread_id")
        comment_id = request.POST.get("comment_id")

        thread = get_object_or_404(Thread, pk=thread_id)
        parent_comment = None
        if comment_id:
            parent_comment = get_object_or_404(Comment, pk=comment_id)

        # Ensure thred content and thread images are not both empty.
        if len(content_list[0]) == 0 and int(image_count_list[0]) == 0:
            messages.warning(
                request, "You have to provide some content to create reply."
            )
            return redirect("thread:feed")
        # One comment case
        cmt = create_cmt(
            content=content_list[0],
            user=request.user,
            thread=thread,
            parent_comment=parent_comment,
        )
        create_cmt_images(
            image_list=image_list[: int(image_count_list[0])], comment=cmt
        )
        # More than one comment case
        if len(content_list) > 1:
            i = 1
            while i < len(content_list):
                child_cmt = create_cmt(
                    content=content_list[i],
                    user=request.user,
                    thread=thread,
                    parent_comment=cmt,
                )
                left = 0
                for j in range(i):
                    left += int(image_count_list[j])
                right = left + int(image_count_list[i])
                create_cmt_images(image_list=image_list[left:right], comment=child_cmt)
                i += 1

        messages.success(request, "Reply created successfully.")

        if parent_comment:
            return redirect(
                "thread:get_reply",
                username=parent_comment.user.username,
                id=int(comment_id),
            )
        else:
            return redirect(
                "thread:get_thread", username=thread.user.username, id=int(thread_id)
            )

    return redirect("thread:feed")


@login_required
def get_thread(request, username, id):
    thread = get_object_or_404(Thread, pk=id)
    direct_comments = Comment.objects.filter(thread=thread, parent_comment=None)

    paginator = Paginator(direct_comments, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"thread": thread, "direct_comments": page_obj}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(
            request,
            "thread/htmx/partials/_more_comment_section_for_thread_page.html",
            context,
        )
    if request.META.get("HTTP_HX_REQUEST"):
        return render(request, "thread/htmx/thread_page.html", context)
    return render(request, "thread/f_thread_page.html", context)


@login_required
def get_reply(request, username, id):
    comment = get_object_or_404(Comment, pk=id)
    sub_comments = Comment.objects.filter(parent_comment=comment, thread=comment.thread)

    paginator = Paginator(sub_comments, 7)
    page_number = request.GET.get("page") or 1

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_number = 1
    except EmptyPage:
        page_number = 1

    page_obj = paginator.page(page_number)
    context = {"comment": comment, "sub_comments": page_obj}
    if request.META.get("HTTP_HX_REQUEST") and int(page_number) > 1:
        return render(
            request,

thread/templates/thread/htmx/reply_page.html
<!-- Reply page -->
<div class="w-full pb-16">
    <!-- Banner -->
    <div class="flex bg-white border-b-2 justify-between px-3 py-4 sticky top-0 z-50">
        <div class="text-center cursor-pointer"
             onclick="window.history.go(-1); return false;">Back</div>
        <div class="text-center font-bold">Reply</div>
        <div class="opacity-0">gibrish</div>
    </div>
    <!-- The margin dude-->
    <div class="opacity-0 my-3"></div>
    <!-- The thread -->
    {% include "accounts/partials/_profile_reply_thread.html" with cmt=comment %}
    <!-- The Hierarchy comments -->
    {% for cmt  in comment.get_comment_hierarchy %}
        {% include "thread/htmx/partials/_h_comment.html" with cmt=cmt %}
    {% endfor %}
    <!-- The comment -->
    {% include "thread/htmx/partials/_comment.html" with comment=comment %}
    {% if sub_comments %}
        <!-- Child comments -->
        {% include "thread/htmx/partials/_comment_section_for_reply_page.html" with sub_comments=sub_comments %}
    {% else %}
        <div class="pb-16"></div>
    {% endif %}
</div>

thread/templates/thread/htmx/search.html
{% load static %}
<div class="flex flex-col justify-start pb-14 sm:pb-20 items-center w-full">
    <!-- Thread logo-->
    <div class="text-black py-4">
        <svg xmlns="http://www.w3.org/2000/svg"
             aria-label="Threads"
             class="w-8 h-8 sm:w-12 sm:h-12"
             stroke="currentColor"
             fill="currentColor"
             viewBox="0 0 192 192">
            <path class="x19hqcy" d="M141.537 88.9883C140.71 88.5919 139.87 88.2104 139.019 87.8451C137.537 60.5382 122.616 44.905 97.5619 44.745C97.4484 44.7443 97.3355 44.7443 97.222 44.7443C82.2364 44.7443 69.7731 51.1409 62.102 62.7807L75.881 72.2328C81.6116 63.5383 90.6052 61.6848 97.2286 61.6848C97.3051 61.6848 97.3819 61.6848 97.4576 61.6855C105.707 61.7381 111.932 64.1366 115.961 68.814C118.893 72.2193 120.854 76.925 121.825 82.8638C114.511 81.6207 106.601 81.2385 98.145 81.7233C74.3247 83.0954 59.0111 96.9879 60.0396 116.292C60.5615 126.084 65.4397 134.508 73.775 140.011C80.8224 144.663 89.899 146.938 99.3323 146.423C111.79 145.74 121.563 140.987 128.381 132.296C133.559 125.696 136.834 117.143 138.28 106.366C144.217 109.949 148.617 114.664 151.047 120.332C155.179 129.967 155.42 145.8 142.501 158.708C131.182 170.016 117.576 174.908 97.0135 175.059C74.2042 174.89 56.9538 167.575 45.7381 153.317C35.2355 139.966 29.8077 120.682 29.6052 96C29.8077 71.3178 35.2355 52.0336 45.7381 38.6827C56.9538 24.4249 74.2039 17.11 97.0132 16.9405C119.988 17.1113 137.539 24.4614 149.184 38.788C154.894 45.8136 159.199 54.6488 162.037 64.9503L178.184 60.6422C174.744 47.9622 169.331 37.0357 161.965 27.974C147.036 9.60668 125.202 0.195148 97.0695 0H96.9569C68.8816 0.19447 47.2921 9.6418 32.7883 28.0793C19.8819 44.4864 13.2244 67.3157 13.0007 95.9325L13 96L13.0007 96.0675C13.2244 124.684 19.8819 147.514 32.7883 163.921C47.2921 182.358 68.8816 191.806 96.9569 192H97.0695C122.03 191.827 139.624 185.292 154.118 170.811C173.081 151.866 172.51 128.119 166.26 113.541C161.776 103.087 153.227 94.5962 141.537 88.9883ZM98.4405 129.507C88.0005 130.095 77.1544 125.409 76.6196 115.372C76.2232 107.93 81.9158 99.626 99.0812 98.6368C101.047 98.5234 102.976 98.468 104.871 98.468C111.106 98.468 116.939 99.0737 122.242 100.233C120.264 124.935 108.662 128.946 98.4405 129.507Z" />
        </svg>
    </div>
    <div class="flex flex-col justify-start w-full px-3">
        <!-- Search input-->
        <label class="relative w-full">
            <div class="absolute top-5 left-4">
                <svg xmlns="http://www.w3.org/2000/svg"
                     fill="none"
                     viewBox="0 0 24 24"
                     stroke-width="1.5"
                     stroke="currentColor"
                     class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
                </svg>
            </div>
            <input type="search"
                   name="search"
                   id="search"
                   placeholder="Search"
                   autofocus
                   class="p-5 pl-14 border-gray-400 w-full rounded-2xl border bg-gray-100 focus:outline-none"
                   hx-post="{% url 'thread:search_query' %}"
                   hx-trigger="keyup changed delay:500ms, search"
                   hx-target="#search-results"
                   hx-indicator="#search-query-indicator">
        </label>
        <!-- Profiles -->
        <div class="relative">
            <div id="search-results">
                {% for u in page_obj %}
                    {% if not u == user %}
                        {% if forloop.last and page_obj.next_page_number %}
                            <div class="flex pt-4 space-x-3 cursor-pointer"
                                 hx-get="{% url 'thread:search' %}?page={{ page_obj.next_page_number }}"
                                 hx-trigger="intersect once"
                                 hx-indicator="#search-query-indicator"
                                 hx-sync="#search:abort"
                                 hx-swap="afterend">
                                {% include "thread/htmx/partials/_avatar.html" with u=u show_follower=True %}
                            </div>
                        {% elif forloop.last %}
                            <div class="flex pt-4 space-x-3 cursor-pointer">
                                {% include "thread/htmx/partials/_avatar.html" with u=u show_follower=True %}
                            </div>
                            <div class="text-center">That's all.</div>
                        {% else %}
                            <div class="flex pt-4 space-x-3 cursor-pointer">
                                {% include "thread/htmx/partials/_avatar.html" with u=u show_follower=True %}
                            </div>
                        {% endif %}
                    {% elif u == user and forloop.last %}
                        <div class="text-center">That's all.</div>
                    {% endif %}
                {% empty %}
                    <dir>No profiles found.</dir>
                {% endfor %}
            </div>
            <!-- HTMX more search indicator -->
            <div id="more-search-indicator"
                 class="htmx-indicator w-full py-4 pb-11 flex justify-center">
                <svg width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     xmlns="http://www.w3.org/2000/svg">
                    <style>.spinner_7WDj{transform-origin:center;animation:spinner_PBVY .75s linear infinite}@keyframes spinner_PBVY{100%{transform:rotate(360deg)}}</style>
                    <path d="M12,1A11,11,0,1,0,23,12,11,11,0,0,0,12,1Zm0,19a8,8,0,1,1,8-8A8,8,0,0,1,12,20Z" opacity=".25" />
                    <circle class="spinner_7WDj" cx="12" cy="2.5" r="1.5" />
                </svg>
            </div>
            <!-- HTMX search query indicator -->
            <div id="search-query-indicator"
                 class="htmx-indicator w-full flex justify-center items-center absolute min-h-[80vh] top-0 bg-white inset-x-0">
                <svg width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     xmlns="http://www.w3.org/2000/svg">
                    <style>.spinner_7WDj{transform-origin:center;animation:spinner_PBVY .75s linear infinite}@keyframes spinner_PBVY{100%{transform:rotate(360deg)}}</style>
                    <path d="M12,1A11,11,0,1,0,23,12,11,11,0,0,0,12,1Zm0,19a8,8,0,1,1,8-8A8,8,0,0,1,12,20Z" opacity=".25" />
                    <circle class="spinner_7WDj" cx="12" cy="2.5" r="1.5" />
                </svg>
            </div>
        </div>
    </div>
</div>
<script defer src="{% static 'js/search.js' %}"></script>

thread/templates/thread/htmx/thread_page.html
<!-- Thread Page -->
<div class="w-full pb-16">
    <!-- Banner -->
    <div class="flex bg-white border-b-2 justify-between px-3 py-4 sticky top-0 z-50">
        <div class="text-center cursor-pointer"
             onclick="window.history.go(-1); return false;">Back</div>
        <div class="text-center font-bold">Thread</div>
        <div class="opacity-0">gibrish</div>
    </div>
    <!-- Margin dude -->
    <div class="opacity-0 my-3"></div>
    <!-- Thread -->
    {% include "thread/htmx/partials/_thread_section.html" with thread=thread %}
    <!-- Comment section -->
    {% include "thread/htmx/partials/_comment_section_for_thread_page.html" with direct_comments=direct_comments %}
</div>