core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("thread.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thread/urls.py
from django.urls import path
from . import views


app_name = "thread"

urlpatterns = [
    path("", views.home, name="home"),
    path("feed/", views.feed, name="feed"),
    path("following-feed/", views.following_feed, name="following_feed"),
    path("search/", views.search, name="search"),
    path("search-query/", views.search_query, name="search_query"),
    path("create-thread/", views.create_thread, name="create_thread"),
    path("create-reply/", views.create_reply, name="create_reply"),
    # htmx form related (thread and comment)
    path(
        "thread-reply-form/<int:id>/",
        views.get_thread_reply_form,
        name="get_thread_reply_form",
    ),
    path(
        "comment-reply-form/<int:id>/",
        views.get_comment_reply_form,
        name="get_comment_reply_form",
    ),
    path("thread-form-unit/", views.get_thread_form_unit, name="get_thread_form_unit"),
    path("reply-form-unit/", views.get_reply_form_unit, name="get_reply_form_unit"),
    # htmx like features related routes
    path(
        "like-toggle/thread/<int:id>/",
        views.like_thread_toggle,
        name="like_thread_toggle",
    ),
    path(
        "like-toggle/comment/<int:id>/",
        views.like_comment_toggle,
        name="like_comment_toggle",
    ),
    # htmx detail page(thread and reply)
    path("<str:username>/threads/<int:id>/", views.get_thread, name="get_thread"),
    path("<str:username>/replies/<int:id>/", views.get_reply, name="get_reply"),
    # htmx repost threads or comments
    path(
        "repost-toggle/thread/<int:id>/",
        views.repost_thread_toggle,
        name="repost_thread_toggle",
    ),
    path(
        "repost-toggle/comment/<int:id>/",
        views.repost_comment_toggle,
        name="repost_comment_toggle",
    ),
    # htmx get likes
    path(
        "<str:username>/threads-likes/<int:id>/",
        views.get_thread_likes,
        name="get_thread_likes",
    ),
    path(
        "<str:username>/replies-likes/<int:id>/",
        views.get_reply_likes,
        name="get_reply_likes",
    ),
    # notification htmx
    path("notification/", views.notification, name="notification"),
    path("check-reddot/", views.check_reddot, name="check_reddot"),
]

templates/partials/htmx/_comment_reply_form.html
{% load static %}
{% load extra %}
{% load thumbnail %}
<!-- Reply comment -->
{% include "partials/htmx/components/_reply_comment.html" with comment=comment %}
<!-- Reply form-->
<form enctype="multipart/form-data"
      action="{% url 'thread:create_reply' %}"
      method="post"
      id="comment-reply-form"
      class="w-full">
    {% csrf_token %}
    <!-- Unit container -->
    <div id="reply-unit-container">
        <!-- Upper unit -->
        <div class="reply-unit flex px-2 sm:px-4 space-x-3 sm:space-x-4 text-base sm:text-lg mt-2">
            <!-- Left -->
            <div class="flex flex-col items-center">
                {% include "partials/components/_profile_picture.html" with u=user %}
                <div class="bg-neutral-content w-[2px] grow my-3 z-10"></div>
                {% if user.myuser.profile_picture %}
                    <div class="avatar opacity-30 reply-smallter">
                        <div class="w-5 sm:w-7 rounded-full">
                            {% thumbnail user.myuser.profile_picture '60' as im %}
                                <img src="{{ im.url }}"
                                     srcset="{% thumbnail user.myuser.profile_picture '50' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %}"
                                     alt="Profile picture of {{ user.username }}"
                                     sizes="100vw"
                                     width="{{ im.width }}"
                                     height="{{ im.height }}"
                                     class="w-full" />
                            {% endthumbnail %}
                        </div>
                    </div>
                {% else %}
                    <div class="avatar placeholder opacity-30 reply-smallter">
                        <div class="bg-neutral-focus text-neutral-content rounded-full w-5 sm:w-7">
                            <span class="text-xs uppercase">{{ user.username|ecut }}</span>
                        </div>
                    </div>
                {% endif %}
            </div>
            <!-- Right -->
            <div class="w-full ">
                <!-- Username-->
                <div class="flex w-full justify-between">
                    <div class="font-semibold text-black">{{ user.username }}</div>
                    <span class="text-gray-400 text-lg px-2 hidden cursor-pointer reply-delete-unit">x</span>
                </div>
                <!-- Form inner unit -->
                <div class="flex flex-col mt-3 space-y-2">
                    <textarea name="content"
                              placeholder="Reply to {{comment.user.username}}"
                              autofocus
                              width="100%"
                              height="auto"
                              maxlength="420"
                              class="content border-none no-scrollbar focus:outline-none focus:border-none h-auto resize-none"></textarea>
                    <!-- Paper clip -->
                    <div class="reply-clip">
                        <label>
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 fill="none"
                                 viewBox="0 0 24 24"
                                 stroke-width="1.5"
                                 stroke="currentColor"
                                 class="w-6 h-6 cursor-pointer">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <input type="file"
                                   name="reply_images"
                                   accept="image/*"
                                   multiple
                                   class="hidden reply-images">
                        </label>
                    </div>
                    <!-- Image container -->
                    <div class="carousel carousel-center min-w-full p-4 pl-12 -ml-12 space-x-2 sm:space-x-4 bg-white rounded-box hidden transition new-reply-image-container">
                    </div>
                    <!-- Image count -->
                    <input type="number"
                           name="image_count"
                           value="0"
                           hidden
                           class="reply-image-count">
                    <!-- Parent comment and thread -->
                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                    <input type="hidden" name="thread_id" value="{{ comment.thread.id }}">
                    <!-- Paddind dude -->
                    <div class="opacity-0 pb-6"></div>
                    <!-- Att btn-->
                    <div class="flex items-center space-x-3 reply-att-parent">
                        <button class="text-gray-200 w-fit reply-att"
                                hx-get="{% url 'thread:get_reply_form_unit' %}"
                                hx-swap="beforeend"
                                disabled
                                hx-indicator="#reply-att-indicator"
                                hx-target="#reply-unit-container">Add another reply</button>
                        <div id="reply-att-indicator" class="htmx-indicator">
                            <svg width="24"
                                 height="24"
                                 viewBox="0 0 24 24"
                                 xmlns="http://www.w3.org/2000/svg">
                                <style>.spinner_qM83{animation:spinner_8HQG 1.05s infinite}.spinner_oXPr{animation-delay:.1s}.spinner_ZTLf{animation-delay:.2s}@keyframes spinner_8HQG{0%,57.14%{animation-timing-function:cubic-bezier(0.33,.66,.66,1);transform:translate(0)}28.57%{animation-timing-function:cubic-bezier(0.33,0,.66,.33);transform:translateY(-6px)}100%{transform:translate(0)}}</style><circle class="spinner_qM83" cx="4" cy="12" r="3" /><circle class="spinner_qM83 spinner_oXPr" cx="12" cy="12" r="3" /><circle class="spinner_qM83 spinner_ZTLf" cx="20" cy="12" r="3" />
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="flex justify-between w-full pr-4">
        <div class="opacity-0"></div>
        <button type="submit"
                class="font-medium block cursor-pointer py-2 px-4 text-white bg-black rounded-xl">Post</button>
    </div>
</form>
<script defer src="{% static 'js/replyForm.js' %}"></script>

templates/partials/htmx/_reply_form.html
{% load static %}
{% load extra %}
{% if post.thread %}
    <!-- Reply comment -->
    {% include "partials/htmx/components/_reply_comment.html" with comment=post %}
{% else %}
    <!-- Reply thread -->
    {% include "partials/htmx/components/_reply_thread.html" with thread=post %}
{% endif %}
<!-- Reply form-->
<form enctype="multipart/form-data"
      action="{% url 'thread:create_reply' %}"
      method="post"
      class="w-full ">
    {% csrf_token %}
    <!-- Unit container -->
    <div id="reply-unit-container">
        <!-- Upper unit -->
        <div class="reply-unit flex px-2 sm:px-4 space-x-3 sm:space-x-4 text-base sm:text-lg mt-2">
            <!-- Left -->
            <div class="flex flex-col items-center">
                {% include "partials/components/_profile_picture.html" with u=user %}
                <div class="bg-neutral-content w-[2px] grow my-3 z-10"></div>
                {% if user.myuser.profile_picture %}
                    <div class="avatar opacity-30 reply-smallter">
                        <div class="w-5 sm:w-7 rounded-full">
                            <img src="{{ user.myuser.profile_picture.url }}" alt="Profile" />
                        </div>
                    </div>
                {% else %}
                    <div class="avatar placeholder opacity-30 reply-smallter">
                        <div class="bg-neutral-focus text-neutral-content rounded-full w-5 sm:w-7">
                            <span class="text-xs uppercase">{{ user.username|ecut }}</span>
                        </div>
                    </div>
                {% endif %}
            </div>
            <!-- Right -->
            <div class="w-full ">
                <!-- Username-->
                <div class="flex w-full justify-between">
                    <div class="font-semibold text-black">{{ user.username }}</div>
                    <span class="text-gray-400 text-lg px-2 hidden cursor-pointer reply-delete-unit">x</span>
                </div>
                <!-- Form inner unit -->
                <div class="flex flex-col mt-3 space-y-2">
                    <textarea name="content"
                              placeholder="Reply to {{thread.user.username}}"
                              autofocus
                              width="100%"
                              height="auto"
                              maxlength="420"
                              class="content border-none no-scrollbar focus:outline-none focus:border-none h-auto resize-none"></textarea>
                    <!-- Paper clip -->
                    <div class="reply-clip">
                        <label>
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 fill="none"
                                 viewBox="0 0 24 24"
                                 stroke-width="1.5"
                                 stroke="currentColor"
                                 class="w-6 h-6 cursor-pointer">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <input type="file"
                                   name="reply_images"
                                   accept="image/*"
                                   multiple
                                   class="hidden reply-images">
                        </label>
                    </div>
                    <!-- Image container -->
                    <div class="carousel carousel-center min-w-full p-4 pl-12 -ml-12 space-x-2 sm:space-x-4 bg-white rounded-box hidden transition new-reply-image-container">
                    </div>
                    <!-- Image count -->
                    <input type="number"
                           name="image_count"
                           value="0"
                           hidden
                           class="reply-image-count">
                    <!-- Parent thread or comment -->
                    {% if post.thread %}
                        <input type="hidden" name="comment_id" value="{{ post.id }}">
                        <input type="hidden" name="thread_id" value="{{ post.thread.id }}">
                    {% else %}
                        <input type="hidden" name="thread_id" value="{{ post.id }}">
                    {% endif %}
                    <!-- Paddind dude -->
                    <div class="opacity-0 pb-6"></div>
                    <!-- Att btn-->
                    <div class="flex items-center space-x-3 reply-att-parent">
                        <button class="text-gray-200 w-fit reply-att"
                                hx-get="{% url 'thread:get_reply_form_unit' %}"
                                hx-swap="beforeend"
                                disabled
                                hx-indicator="#reply-att-indicator"
                                hx-target="#reply-unit-container">Add another reply</button>
                        <div id="reply-att-indicator" class="htmx-indicator">
                            <svg width="24"
                                 height="24"
                                 viewBox="0 0 24 24"
                                 xmlns="http://www.w3.org/2000/svg">
                                <style>.spinner_qM83{animation:spinner_8HQG 1.05s infinite}.spinner_oXPr{animation-delay:.1s}.spinner_ZTLf{animation-delay:.2s}@keyframes spinner_8HQG{0%,57.14%{animation-timing-function:cubic-bezier(0.33,.66,.66,1);transform:translate(0)}28.57%{animation-timing-function:cubic-bezier(0.33,0,.66,.33);transform:translateY(-6px)}100%{transform:translate(0)}}</style><circle class="spinner_qM83" cx="4" cy="12" r="3" /><circle class="spinner_qM83 spinner_oXPr" cx="12" cy="12" r="3" /><circle class="spinner_qM83 spinner_ZTLf" cx="20" cy="12" r="3" />
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="flex justify-between w-full">
        <div class="opacity-0"></div>
        <input type="submit"
               name="submit"
               value="Post"
               class="font-medium block cursor-pointer py-4 pr-4 text-blue-600">
    </div>
</form>
<script defer src="{% static 'js/replyForm.js' %}"></script>

templates/partials/htmx/_reply_form_unit.html
{% load extra %}
{% load thumbnail %}
<!-- Reply form unit -->
<div class="reply-unit flex px-2 sm:px-4 space-x-3 sm:space-x-4 text-base sm:text-lg mt-2 ">
    <!-- Left -->
    <div class="flex flex-col items-center">
        {% include "partials/components/_profile_picture.html" with u=user %}
        <div class="bg-neutral-content w-[2px] grow my-3 z-10"></div>
        {% if user.myuser.profile_picture %}
            <div class="avatar opacity-30 smallter">
                <div class="w-5 sm:w-7 rounded-full">
                    {% thumbnail user.myuser.profile_picture '60' as im %}
                        <img src="{{ im.url }}"
                             srcset="{% thumbnail user.myuser.profile_picture '50' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %}"
                             alt="Profile picture of {{ user.username }}"
                             sizes="100vw"
                             width="{{ im.width }}"
                             height="{{ im.height }}"
                             class="w-full" />
                    {% endthumbnail %}
                </div>
            </div>
        {% else %}
            <div class="avatar placeholder opacity-30 reply-smallter">
                <div class="bg-neutral-focus text-neutral-content rounded-full w-5 sm:w-7">
                    <span class="text-xs uppercase">{{ user.username|ecut }}</span>
                </div>
            </div>
        {% endif %}
    </div>
    <!-- Right -->
    <div class="w-full ">
        <!-- Username-->
        <div class="flex w-full justify-between">
            <div class="font-semibold text-black">{{ user.username }}</div>
            <span class="text-gray-400 text-lg px-2 cursor-pointer reply-delete-unit">x</span>
        </div>
        <!-- reply Form inner unit -->
        <div class="flex flex-col mt-3 space-y-2 inner-unit">
            <textarea name="content"
                      placeholder="Say more..."
                      autofocus
                      width="100%"
                      height="auto"
                      maxlength="420"
                      class="content border-none no-scrollbar focus:outline-none focus:border-none h-auto resize-none"></textarea>
            <!-- Paper clip -->
            <div class="reply-clip">
                <label>
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6 cursor-pointer">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                    </svg>
                    <input type="file"
                           name="reply_images"
                           accept="image/*"
                           multiple
                           class="hidden reply-images">
                </label>
            </div>
            <!-- Reply Image container -->
            <div class="carousel carousel-center min-w-full p-4 pl-12 -ml-12 space-x-2 sm:space-x-4 bg-white rounded-box hidden transition new-reply-image-container">
            </div>
            <!-- Image count -->
            <input type="number"
                   name="image_count"
                   value="0"
                   hidden
                   class="reply-image-count">
            <!-- Paddind dude -->
            <div class="opacity-0 pb-6"></div>
            <!-- Reply Att btn-->
            <div class="flex items-center space-x-3 reply-att-parent">
                <button class="text-gray-200 w-fit reply-att"
                        hx-get="{% url 'thread:get_reply_form_unit' %}"
                        hx-swap="beforeend"
                        disabled
                        hx-indicator="#reply-att-indicator"
                        hx-target="#reply-unit-container">Add to thread</button>
                <div id="reply-att-indicator" class="htmx-indicator">
                    <svg width="24"
                         height="24"
                         viewBox="0 0 24 24"
                         xmlns="http://www.w3.org/2000/svg">
                        <style>.spinner_qM83{animation:spinner_8HQG 1.05s infinite}.spinner_oXPr{animation-delay:.1s}.spinner_ZTLf{animation-delay:.2s}@keyframes spinner_8HQG{0%,57.14%{animation-timing-function:cubic-bezier(0.33,.66,.66,1);transform:translate(0)}28.57%{animation-timing-function:cubic-bezier(0.33,0,.66,.33);transform:translateY(-6px)}100%{transform:translate(0)}}</style><circle class="spinner_qM83" cx="4" cy="12" r="3" /><circle class="spinner_qM83 spinner_oXPr" cx="12" cy="12" r="3" /><circle class="spinner_qM83 spinner_ZTLf" cx="20" cy="12" r="3" />
                    </svg>
                </div>
            </div>
        </div>
    </div>
</div>

templates/partials/htmx/_thread_reply_form.html
{% load static %}
{% load extra %}
{% load thumbnail %}
<!-- Reply thread -->
{% include "partials/htmx/components/_reply_thread.html" with thread=thread %}
<!-- Reply form-->
<form enctype="multipart/form-data"
      action="{% url 'thread:create_reply' %}"
      method="post"
      id="thread-reply-form"
      class="w-full">
    {% csrf_token %}
    <!-- Unit container -->
    <div id="reply-unit-container">
        <!-- Upper unit -->
        <div class="reply-unit flex px-2 sm:px-4 space-x-3 sm:space-x-4 text-base sm:text-lg mt-2">
            <!-- Left -->
            <div class="flex flex-col items-center">
                {% include "partials/components/_profile_picture.html" with u=user %}
                <div class="bg-neutral-content w-[2px] grow my-3 z-10"></div>
                {% if user.myuser.profile_picture %}
                    <div class="avatar opacity-30 reply-smallter">
                        <div class="w-5 sm:w-7 rounded-full">
                            {% thumbnail user.myuser.profile_picture '60' as im %}
                                <img src="{{ im.url }}"
                                     srcset="{% thumbnail user.myuser.profile_picture '50' as im %}  {{ im.url }} {{ im.x }}w{% endthumbnail %}"
                                     alt="Profile picture of {{ user.username }}"
                                     sizes="100vw"
                                     width="{{ im.width }}"
                                     height="{{ im.height }}"
                                     class="w-full" />
                            {% endthumbnail %}
                        </div>
                    </div>
                {% else %}
                    <div class="avatar placeholder opacity-30 reply-smallter">
                        <div class="bg-neutral-focus text-neutral-content rounded-full w-5 sm:w-7">
                            <span class="text-xs uppercase">{{ user.username|ecut }}</span>
                        </div>
                    </div>
                {% endif %}
            </div>
            <!-- Right -->
            <div class="w-full ">
                <!-- Username-->
                <div class="flex w-full justify-between">
                    <div class="font-semibold text-black">{{ user.username }}</div>
                    <span class="text-gray-400 text-lg px-2 hidden cursor-pointer reply-delete-unit">x</span>
                </div>
                <!-- Form inner unit -->
                <div class="flex flex-col mt-3 space-y-2">
                    <textarea name="content"
                              placeholder="Reply to {{thread.user.username}}"
                              autofocus
                              width="100%"
                              height="auto"
                              maxlength="420"
                              class="content border-none no-scrollbar focus:outline-none focus:border-none h-auto resize-none"></textarea>
                    <!-- Paper clip -->
                    <div class="reply-clip">
                        <label>
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 fill="none"
                                 viewBox="0 0 24 24"
                                 stroke-width="1.5"
                                 stroke="currentColor"
                                 class="w-6 h-6 cursor-pointer">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <input type="file"
                                   name="reply_images"
                                   accept="image/*"
                                   multiple
                                   class="hidden reply-images">
                        </label>
                    </div>
                    <!-- Image container -->
                    <div class="carousel carousel-center min-w-full p-4 pl-12 -ml-12 space-x-2 sm:space-x-4 bg-white rounded-box hidden transition new-reply-image-container">
                    </div>
                    <!-- Image count -->
                    <input type="number"
                           name="image_count"
                           value="0"
                           hidden
                           class="reply-image-count">
                    <!-- Parent thread  -->
                    <input type="hidden" name="thread_id" value="{{ thread.id }}">
                    <!-- Paddind dude -->
                    <div class="opacity-0 pb-6"></div>
                    <!-- Att btn-->
                    <div class="flex items-center space-x-3 reply-att-parent">
                        <button class="text-gray-200 w-fit reply-att"
                                hx-get="{% url 'thread:get_reply_form_unit' %}"
                                hx-swap="beforeend"
                                disabled
                                hx-indicator="#reply-att-indicator"
                                hx-target="#reply-unit-container">Add another reply</button>
                        <div id="reply-att-indicator" class="htmx-indicator">
                            <svg width="24"
                                 height="24"
                                 viewBox="0 0 24 24"
                                 xmlns="http://www.w3.org/2000/svg">
                                <style>.spinner_qM83{animation:spinner_8HQG 1.05s infinite}.spinner_oXPr{animation-delay:.1s}.spinner_ZTLf{animation-delay:.2s}@keyframes spinner_8HQG{0%,57.14%{animation-timing-function:cubic-bezier(0.33,.66,.66,1);transform:translate(0)}28.57%{animation-timing-function:cubic-bezier(0.33,0,.66,.33);transform:translateY(-6px)}100%{transform:translate(0)}}</style><circle class="spinner_qM83" cx="4" cy="12" r="3" /><circle class="spinner_qM83 spinner_oXPr" cx="12" cy="12" r="3" /><circle class="spinner_qM83 spinner_ZTLf" cx="20" cy="12" r="3" />
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="flex justify-between w-full pr-4">
        <div class="opacity-0"></div>
        <button type="submit"
                class="font-medium block cursor-pointer py-2 px-4 text-white bg-black rounded-xl">Post</button>
    </div>
</form>
<script defer src="{% static 'js/replyForm.js' %}"></script>